### ISSUE TITLE
calcGDP throws an error of repeated IMF download

### ISSUE THREAD

**Issue by cchrisgong** [pik-piam/mrdrivers#33]
hey Johannes, 

when running
x <- calcOutput("GDP", aggregate = F)

Falk and I both run into the same error here:
```
~~~~ Run downloadSource(type = "IMF")
Error: Source folder for source "IMF" does already exist. Delete that folder or call downloadSource(..., overwrite = TRUE) if you want to re-download.
```
This is because executing this line the script (somewhere) tries to download IMF twice (so manually deleting the IMF folder doesn't help). 

Could you please fix it? Thanks!

**Comment by johanneskoch94** [comment]
Hi Chris, I'm on it! Are you running this locally or on the cluster?

**Comment by cchrisgong** [comment]
Thanks a bunch! I run it locally, but I don't know about Falk

**Comment by cchrisgong** [comment]
@fbenke-pik

**Comment by fbenke-pik** [comment]
For me, this happens when I run it locally, as well.

**Comment by johanneskoch94** [comment]
Ok, I need to look into this further and probably check with Jan why this isn't cached properly.. sry! For now, please manually copy the IMD folder from /p/projects/rd3mod/inputdata/sources, or run `readSource("IMF")` once, before running `calcOutput("GDP")`.
