### ISSUE TITLE
Tests still fail

### ISSUE THREAD

**Issue by mikapfl** [pik-piam/mrdrivers#48]
Hi,

continuing from https://github.com/pik-piam/lucode2/issues/85 , the tests are still failing for me:

```r
r$> devtools::test()
ℹ Loading mrdrivers
Loading required package: madrat
Loading required package: magclass
ℹ Testing mrdrivers
✔ | F W S  OK | Context
✔ |     1   0 | calcOutput_sets                                                                                                             
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error: invalid version specification ‘6402’
```

I don't really understand what is happening there.

Cheers,

Mika

**Comment by johanneskoch94** [comment]
Ok, I don't understand it yet either, but at least the warnings are gone.

**Comment by johanneskoch94** [comment]
Ah, I think it has to do with the cli package and VTE_TERMINAL version. Running devtools::test() from Rstudio doesn't throw the error, that's what led me down this path. The issue is addressed here r-lib/cli#441 and here r-lib/cli#445. This https://github.com/r-lib/cli/issues/441#issuecomment-1090558541 worked for me.

**Comment by mikapfl** [comment]
yay, now it is skipping all tests for me :wink:

**Comment by johanneskoch94** [comment]
Great! :) If you now want to run the tests, you have to adjust the madrat_mainfolder path - as indicated in the skip-message. Depending on what sources and mappings you have locally, I expect different errors (or success of course, if you have everything necessary). I probably should add a check at the start, to make sure that all requirements are met.. Didn't get to that yet..
