### ISSUE TITLE
No citable source for GDP data.

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrdrivers#56]
The documentation of [`calcGDP()`](https://github.com/pik-piam/mrdrivers/blob/eb1da620d641ff8df83dbe8861a0e320400f3527/R/calcGDP.R) does not contain any citable source for GDP data.  Like one would need for _doing science_.

- https://github.com/pik-piam/mrdrivers/blob/eb1da620d641ff8df83dbe8861a0e320400f3527/R/calcGDP.R#L49
And what happens if `GDPCalib` is `NULL`?

- https://github.com/pik-piam/mrdrivers/blob/eb1da620d641ff8df83dbe8861a0e320400f3527/R/calcGDP.R#L65
And what happens if `GDPPast` is `NULL`?

- https://github.com/pik-piam/mrdrivers/blob/eb1da620d641ff8df83dbe8861a0e320400f3527/R/calcGDP.R#L82
And what happens if `GDPFuture` is `NULL`?

- https://github.com/pik-piam/mrdrivers/blob/eb1da620d641ff8df83dbe8861a0e320400f3527/R/calcGDP.R#L85
Besides being completely insufficient as a source, the link is also dead.

I would really like to know how https://github.com/pik-piam/mrdrivers/commit/ec02c71c7599a5bd2025ef8866d68390214399be was supposed to provide anything citable.

-----

https://github.com/pik-piam/mrdrivers/blob/eb1da620d641ff8df83dbe8861a0e320400f3527/R/calcGDP.R#L25-L28
At least somebody had fun.

**Comment by johanneskoch94** [comment]
Maybe we should add Code of Conducts to our R-packages Michaja, so that you can learn how to formulate an issue politely. Like one should be able to _when working in a team_.

I'm sorry my documentation fixes weren't to your satisfaction. I'll try to clarify the documentation and add references. Could you perhaps share a link of a madrat function documented correctly, so that I can copy the format? Thank you.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Maybe we should add Code of Conducts to our R-packages Michaja, so that you can learn how to formulate an issue politely. Like one should be able to _when working in a team_.

Sure.  Let's the include to not willy-nilly close bug reports because one changed _something_ regarding the files concerned.  Asking for review on merge requests could help in that regard.

> I'm sorry my documentation fixes weren't to your satisfaction. I'll try to clarify the documentation and add references. Could you perhaps share a link of a madrat function documented correctly, so that I can copy the format? Thank you.

Simple: Anything you would put in a paper to reference the data going into REMIND, and that you wouldn't expect to get rejected by the reviewers or editors.

**Comment by johanneskoch94** [comment]
Please Michaja, I'm having no luck finding a single calc function in mrremind with citable sources.. could you just point me to one. I don't need to know what to cite, I would like to add the references in the right place. Are they normally under a certain section title, at the begging or end of the documentation, are they only on the calc level, or also on the download, read and convert levels, etc...
